name: Docker Compose Test

on:
  push:
    branches:
      - ubicloud-benchmark
      - '*.x'
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: true
      matrix:
        runner:
          - 'ubuntu-22.04'
          - 'ubicloud-standard-4'
          - 'ubicloud-standard-8'
          - 'ubicloud-standard-16'
          - 'ubicloud-premium-4'
          - 'ubicloud-premium-8'
          - 'ubicloud-premium-16'
    name: ${{ matrix.runner }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: 'sail'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: dom, curl, libxml, mbstring, zip, fileinfo
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: none
        env:
          runner:  ${{ matrix.runner == 'ubuntu-22.04' && 'github' || 'ubicloud' }}

      - name: Create a new laravel application
        run: composer create-project laravel/laravel app "12.x" --remove-vcs --no-interaction --prefer-dist

      - name: Link Sail Repository
        run: |
          composer config minimum-stability dev
          composer config repositories.sail path ../sail
          composer require laravel/sail:* --dev -W
        working-directory: app

      - name: Install Sail into App
        run: |
          php artisan sail:install --php=8.4 --no-interaction
          php artisan sail:publish --no-interaction
        working-directory: app

      - name: Remove Sail
        run: composer remove laravel/sail --dev --no-interaction -W
        working-directory: app

      - name: Start Sail Container
        run: ../sail/bin/sail up -d --wait
        working-directory: app

      - name: Run Migrations
        run: ../sail/bin/sail artisan migrate --no-interaction
        working-directory: app

      - name: Run Tests in Sail Container
        run: ../sail/bin/sail test
        working-directory: app

      - name: Stop Sail Container
        run: ../sail/bin/sail down
        working-directory: app
